[[testcase]]
savePath="./tmp"
name="demoCase1" #reportName
description="This is demoCase1" #optional
timeout="5" #minutes, optional ,default is 20 * time.Minute
maxRetry="3" #optional ,default is 1
date_range="past_2_days"#"2019/04/02,2019/04/04"#
dimensions="Network ID,Network Name,Ad Unit ID,Event Date"#"Network Name,Network ID"
metrics="Gross Delivered Impressions,Net Delivered Impressions"#"Net Delivered Impressions"
filters="{}"#'{"Network ID":{"type":"number","values":[{"condition":"is_equal_to","value":"1234999"}]},"Delivery Method":{"type":"string","values":[{"condition":"contains","value":"asd"}]}}'

[[testcase]]
savePath="./tmp"
name="demoCase2"
description="This is demoCase2"
date_range="2019/04/02,2019/04/04"
dimensions="Network ID,Ad Unit ID,Network Name"#"Network Name,Network ID"
filters="{}"#'{"Network ID":{"type":"number","values":[{"condition":"is_equal_to","value":"1234999"}]},"Delivery Method":{"type":"string","values":[{"condition":"contains","value":"asd"}]}}'
metrics="Auto-played Impressions,Auto-refreshed Impressions,Net Delivered Impressions"#"Net Delivered Impressions"

[[testcase]]
savePath="./tmp/"
name="demoCase3"
description="This is demoCase3"
date_range="last_full_day"#"2019/04/02,2019/04/04"#
dimensions="Network ID,Ad Unit ID,Network Name,"
filters='{"Network ID":{"type":"number","values":[{"condition":"is_equal_to","value":"1234999"}]},"Delivery Method":{"type":"string","values":[{"condition":"contains","value":"asd"}]}}'
metrics="Auto-played Impressions,Auto-refreshed Impressions,Net Delivered Impressions,"#"Net Delivered Impressions"
